/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DemoConvexImport } from './routes/demo.convex'
import { Route as BookCreateImport } from './routes/book.create'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DemoConvexRoute = DemoConvexImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRoute,
} as any)

const BookCreateRoute = BookCreateImport.update({
  id: '/book/create',
  path: '/book/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/book/create': {
      id: '/book/create'
      path: '/book/create'
      fullPath: '/book/create'
      preLoaderRoute: typeof BookCreateImport
      parentRoute: typeof rootRoute
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book/create': typeof BookCreateRoute
  '/demo/convex': typeof DemoConvexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book/create': typeof BookCreateRoute
  '/demo/convex': typeof DemoConvexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/book/create': typeof BookCreateRoute
  '/demo/convex': typeof DemoConvexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/book/create' | '/demo/convex'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/book/create' | '/demo/convex'
  id: '__root__' | '/' | '/book/create' | '/demo/convex'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookCreateRoute: typeof BookCreateRoute
  DemoConvexRoute: typeof DemoConvexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookCreateRoute: BookCreateRoute,
  DemoConvexRoute: DemoConvexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/book/create",
        "/demo/convex"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/book/create": {
      "filePath": "book.create.tsx"
    },
    "/demo/convex": {
      "filePath": "demo.convex.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
