/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BookCreateImport } from './routes/book.create'
import { Route as BookIdImport } from './routes/book.$id'
import { Route as AuthorIdImport } from './routes/author.$id'
import { Route as BookIdIndexImport } from './routes/book.$id.index'
import { Route as BookIdCreateImport } from './routes/book_.$id.create'
import { Route as BookIdReviewsImport } from './routes/book.$id.reviews'
import { Route as BookIdChapterChapterIdImport } from './routes/book_.$id.chapter.$chapterId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BookCreateRoute = BookCreateImport.update({
  id: '/book/create',
  path: '/book/create',
  getParentRoute: () => rootRoute,
} as any)

const BookIdRoute = BookIdImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthorIdRoute = AuthorIdImport.update({
  id: '/author/$id',
  path: '/author/$id',
  getParentRoute: () => rootRoute,
} as any)

const BookIdIndexRoute = BookIdIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BookIdRoute,
} as any)

const BookIdCreateRoute = BookIdCreateImport.update({
  id: '/book_/$id/create',
  path: '/book/$id/create',
  getParentRoute: () => rootRoute,
} as any)

const BookIdReviewsRoute = BookIdReviewsImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BookIdRoute,
} as any)

const BookIdChapterChapterIdRoute = BookIdChapterChapterIdImport.update({
  id: '/book_/$id/chapter/$chapterId',
  path: '/book/$id/chapter/$chapterId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/author/$id': {
      id: '/author/$id'
      path: '/author/$id'
      fullPath: '/author/$id'
      preLoaderRoute: typeof AuthorIdImport
      parentRoute: typeof rootRoute
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdImport
      parentRoute: typeof rootRoute
    }
    '/book/create': {
      id: '/book/create'
      path: '/book/create'
      fullPath: '/book/create'
      preLoaderRoute: typeof BookCreateImport
      parentRoute: typeof rootRoute
    }
    '/book/$id/reviews': {
      id: '/book/$id/reviews'
      path: '/reviews'
      fullPath: '/book/$id/reviews'
      preLoaderRoute: typeof BookIdReviewsImport
      parentRoute: typeof BookIdImport
    }
    '/book_/$id/create': {
      id: '/book_/$id/create'
      path: '/book/$id/create'
      fullPath: '/book/$id/create'
      preLoaderRoute: typeof BookIdCreateImport
      parentRoute: typeof rootRoute
    }
    '/book/$id/': {
      id: '/book/$id/'
      path: '/'
      fullPath: '/book/$id/'
      preLoaderRoute: typeof BookIdIndexImport
      parentRoute: typeof BookIdImport
    }
    '/book_/$id/chapter/$chapterId': {
      id: '/book_/$id/chapter/$chapterId'
      path: '/book/$id/chapter/$chapterId'
      fullPath: '/book/$id/chapter/$chapterId'
      preLoaderRoute: typeof BookIdChapterChapterIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface BookIdRouteChildren {
  BookIdReviewsRoute: typeof BookIdReviewsRoute
  BookIdIndexRoute: typeof BookIdIndexRoute
}

const BookIdRouteChildren: BookIdRouteChildren = {
  BookIdReviewsRoute: BookIdReviewsRoute,
  BookIdIndexRoute: BookIdIndexRoute,
}

const BookIdRouteWithChildren =
  BookIdRoute._addFileChildren(BookIdRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/author/$id': typeof AuthorIdRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/book/create': typeof BookCreateRoute
  '/book/$id/reviews': typeof BookIdReviewsRoute
  '/book/$id/create': typeof BookIdCreateRoute
  '/book/$id/': typeof BookIdIndexRoute
  '/book/$id/chapter/$chapterId': typeof BookIdChapterChapterIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/author/$id': typeof AuthorIdRoute
  '/book/create': typeof BookCreateRoute
  '/book/$id/reviews': typeof BookIdReviewsRoute
  '/book/$id/create': typeof BookIdCreateRoute
  '/book/$id': typeof BookIdIndexRoute
  '/book/$id/chapter/$chapterId': typeof BookIdChapterChapterIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/author/$id': typeof AuthorIdRoute
  '/book/$id': typeof BookIdRouteWithChildren
  '/book/create': typeof BookCreateRoute
  '/book/$id/reviews': typeof BookIdReviewsRoute
  '/book_/$id/create': typeof BookIdCreateRoute
  '/book/$id/': typeof BookIdIndexRoute
  '/book_/$id/chapter/$chapterId': typeof BookIdChapterChapterIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/author/$id'
    | '/book/$id'
    | '/book/create'
    | '/book/$id/reviews'
    | '/book/$id/create'
    | '/book/$id/'
    | '/book/$id/chapter/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/author/$id'
    | '/book/create'
    | '/book/$id/reviews'
    | '/book/$id/create'
    | '/book/$id'
    | '/book/$id/chapter/$chapterId'
  id:
    | '__root__'
    | '/'
    | '/author/$id'
    | '/book/$id'
    | '/book/create'
    | '/book/$id/reviews'
    | '/book_/$id/create'
    | '/book/$id/'
    | '/book_/$id/chapter/$chapterId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthorIdRoute: typeof AuthorIdRoute
  BookIdRoute: typeof BookIdRouteWithChildren
  BookCreateRoute: typeof BookCreateRoute
  BookIdCreateRoute: typeof BookIdCreateRoute
  BookIdChapterChapterIdRoute: typeof BookIdChapterChapterIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthorIdRoute: AuthorIdRoute,
  BookIdRoute: BookIdRouteWithChildren,
  BookCreateRoute: BookCreateRoute,
  BookIdCreateRoute: BookIdCreateRoute,
  BookIdChapterChapterIdRoute: BookIdChapterChapterIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/author/$id",
        "/book/$id",
        "/book/create",
        "/book_/$id/create",
        "/book_/$id/chapter/$chapterId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/author/$id": {
      "filePath": "author.$id.tsx"
    },
    "/book/$id": {
      "filePath": "book.$id.tsx",
      "children": [
        "/book/$id/reviews",
        "/book/$id/"
      ]
    },
    "/book/create": {
      "filePath": "book.create.tsx"
    },
    "/book/$id/reviews": {
      "filePath": "book.$id.reviews.tsx",
      "parent": "/book/$id"
    },
    "/book_/$id/create": {
      "filePath": "book_.$id.create.tsx"
    },
    "/book/$id/": {
      "filePath": "book.$id.index.tsx",
      "parent": "/book/$id"
    },
    "/book_/$id/chapter/$chapterId": {
      "filePath": "book_.$id.chapter.$chapterId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
